Iter15
ospiem/mcollector pull request #16
Opened 2024-01-10 18:48 UTC by ospiem

2024-01-11 18:20 UTC, s-shpak requested changes
Очень достойно, буквально несколько комментариев

2024-01-12 06:05 UTC, ospiem commented on internal/agent/agent.go
>  		case <-reqTicker.C:
Сбор метрик по тикеру в функции Generator и передача их в канал.
Если нет свободных воркеров, то горутина, собирающая метрики будет спать. Как по мне это нормальное поведение, тк сбор и передача метрик идут в реальном времени, если возникли проблемы на стороне сети/сервера, то мы не храним текущие состояние, сбор метрик возобновиться с устранением проблемы. Воркеры будут пытатать отправить метрики в течении 3 ретраев, потом отбросят текущие данные и начнут отправлять новые измерения.

2024-01-12 06:07 UTC, ospiem commented on internal/server/middleware/hash/hash.go
> +func Check(log zerolog.Logger, key string) func(next http.Handler) http.Handler {
Я считаю название достаточно явное, тк функция импортируемая и используется вместе с названием пакета

пример из кода
```go
r.Use(hash.Check(a.Log, a.Cfg.Key))
```

2024-01-12 09:31 UTC, s-shpak requested changes

2024-01-12 09:31 UTC, s-shpak commented on internal/agent/agent.go
>  		case <-reqTicker.C:
Проблема заключается в том, что если воркеры работают медленно, то сбор метрик также блокируется. Эти два процесса должны быть независимыми. В идеале хотелось бы, чтобы:
1. происходит сбор метрик (по тикеру сбора), собранные метрики кешируются
2. при получении сигнала от тикера отправки, основная го-рутина берет закешированные метрики и передает их в канал задач
3. если воркер свободен, то он забирает задачу; если нет, то возможно несколько вариантов. Я бы предложил дропнуть эту задачу, залогировать это и продолжить выполнение

2024-01-14 14:25 UTC, s-shpak requested changes

2024-01-14 14:25 UTC, s-shpak commented on internal/agent/agent.go
> +	l.Debug().Msg("Hello from generator")
deadcode

2024-01-14 14:25 UTC, s-shpak commented on cmd/agent/main.go
> +			fmt.Printf("deque's length %d\n", data.Len())
deadcode

2024-01-14 14:25 UTC, s-shpak commented on cmd/agent/main.go
> +	data := deque.NewDeque[map[string]string]()
Не вижу смысла в использовании очереди: почему бы просто не перезаписывать старое значение, как только получена новая метрика ? Если тз не требует сохранять старые значения, то лучше это не делать

2024-01-14 14:25 UTC, s-shpak commented on cmd/agent/main.go
> +		case <-pollTicker.C:
Мне не очень нравится, что тикеры размазаны по коду: один вызывается здесь, другой - внутри воркер пула. Почему бы не сделать как-то так: https://go.dev/play/p/_Ia2QnRdizj ? Попробуй упростить код: тебе не нужны генераторы и т.п., тебе надо просто запустить воркеры в отдельных го-рутинах и передавать им задачи по мере их поступления

2024-01-15 12:56 UTC, s-shpak requested changes

2024-01-15 12:56 UTC, s-shpak commented on internal/agent/agent.go
> +	mc.coll = append(mc.coll, metrics)
Есть две концептуальные проблемы в очереди метрик на отправку:
1. если метрик генеруируется намного больше, чем отправляется, то на сервер никогда не будут приходить свежие значения
2. размер очереди никак не ограничен, можно случайно исчерпать память

Т.к. в ТЗ ничего не говорится о необходимости отправления всех собраных метрик, то новый пакет, который не получается послать, можно просто дропнуть

2024-01-17 13:09 UTC, merged